// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoSheCrSyN7qmprG-8OblyDZ9gatmD5yM',
    appId: '1:402009767733:web:cdde0afe83b95dc3f3967c',
    messagingSenderId: '402009767733',
    projectId: 'capstone-sampahku',
    authDomain: 'capstone-sampahku.firebaseapp.com',
    storageBucket: 'capstone-sampahku.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWT96AC_iojcT8_iRr4_lv2XTAnhYP1Dw',
    appId: '1:402009767733:android:95c8e95908a38dc4f3967c',
    messagingSenderId: '402009767733',
    projectId: 'capstone-sampahku',
    storageBucket: 'capstone-sampahku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkv4gqJKAVgaXVEtLMqFjJYxCtvHSLPo4',
    appId: '1:402009767733:ios:2a7b2f0016fccc64f3967c',
    messagingSenderId: '402009767733',
    projectId: 'capstone-sampahku',
    storageBucket: 'capstone-sampahku.firebasestorage.app',
    iosBundleId: 'com.example.sampahkuFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkv4gqJKAVgaXVEtLMqFjJYxCtvHSLPo4',
    appId: '1:402009767733:ios:2a7b2f0016fccc64f3967c',
    messagingSenderId: '402009767733',
    projectId: 'capstone-sampahku',
    storageBucket: 'capstone-sampahku.firebasestorage.app',
    iosBundleId: 'com.example.sampahkuFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoSheCrSyN7qmprG-8OblyDZ9gatmD5yM',
    appId: '1:402009767733:web:ac81ecb0ce46dc0df3967c',
    messagingSenderId: '402009767733',
    projectId: 'capstone-sampahku',
    authDomain: 'capstone-sampahku.firebaseapp.com',
    storageBucket: 'capstone-sampahku.firebasestorage.app',
  );
}
